security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        main:
            pattern: ^/

            form_login:
                failure_path: /login
                login_path: /login
                check_path: /login_check

            oauth:
                failure_path: /connect
                login_path: /login
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:           "/login/check-google"
                oauth_user_provider:
                    service: ts.superkicker.provider.oauth

            anonymous:    true
            logout:
                path:           /logout
                target:         /login #where to go after logout


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/signin, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
