ts_superkicker_index:
    path:     /
    defaults: { _controller: ts.superkicker.dashboard.contoller:indexAction }
ts_superkicker_tipp_edit:
    path:     /user/tipp/edit/{matchDay}/{saved}
    defaults: { _controller: ts.superkicker.tip.contoller:editAction, matchDay: 1, saved: 0  }
ts_superkicker_tipp_save:
    path:     /user/tipp/save
    defaults: { _controller: ts.superkicker.tip.contoller:saveAction }
ts_superkicker_match_edit:
    path:     /admin/match/edit/{matchDay}/{saved}
    defaults: { _controller: ts.superkicker.match.contoller:editAction, matchDay: 1, saved: 0  }
ts_superkicker_match_save:
    path:     /admin/match/save
    defaults: { _controller: ts.superkicker.match.contoller:saveAction }
ts_superkicker_club_edit:
    path:     /admin/club/edit/{saved}
    defaults: { _controller: ts.superkicker.club.contoller:editAction, saved: 0  }
ts_superkicker_club_save:
    path:     /admin/club/save
    defaults: { _controller: ts.superkicker.club.contoller:saveAction }

