ts_superkicker_index:
    path:     /
    defaults: { _controller: ts.superkicker.dashboard.contoller:indexAction }
ts_superkicker_tipp_edit:
    path:     /tipp/edit/{matchDay}/{saved}
    defaults: { _controller: ts.superkicker.tip.contoller:editAction, matchDay: 0, saved: 0  }
ts_superkicker_tipp_save:
    path:     /tipp/save
    defaults: { _controller: ts.superkicker.tip.contoller:saveAction }
ts_superkicker_match_edit:
    path:     /match/edit/{match}/{saved}
    defaults: { _controller: ts.superkicker.match.contoller:editAction, match: 0, saved: 0  }
ts_superkicker_match_save:
    path:     /match/save
    defaults: { _controller: ts.superkicker.match.contoller:saveAction }
ts_superkicker_match_list:
    path:     /match/list
    defaults: { _controller: ts.superkicker.match.contoller:listAction }